#
# :author: PN
# :maintainers: PN
# :date: 2019-03-19
# :license: GPL 2.0 or greater
#
# ice-air/import/src/Makefile
#
#

all: \
	output/ARTS_Data_Dictionary.csv.gz \
	output/ARTS_Passenger_Data_FY11.csv.gz \
	output/ARTS_Passenger_Data_FY12.csv.gz \
	output/ARTS_Passenger_Data_FY13.csv.gz \
	output/ARTS_Passenger_Data_FY14.csv.gz \
	output/ARTS_Passenger_Data_FY15.csv.gz \
	output/ARTS_Passenger_Data_FY16.csv.gz \
	output/ARTS_Passenger_Data_FY17.csv.gz \
	output/ARTS_Passenger_Data_FY18.csv.gz \
	output/ARTS_Passenger_Data_FY19.csv.gz

output/ARTS_Data_Dictionary.csv.gz: \
		input/ARTS_Data_Dictionary.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY11.csv.gz: \
		input/ARTS_Passenger_Data_FY11.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY12.csv.gz: \
		input/ARTS_Passenger_Data_FY12.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY13.csv.gz: \
		input/ARTS_Passenger_Data_FY13.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY14.csv.gz: \
		input/ARTS_Passenger_Data_FY14.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY15.csv.gz: \
		input/ARTS_Passenger_Data_FY15.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY16.csv.gz: \
		input/ARTS_Passenger_Data_FY16.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY17.csv.gz: \
		input/ARTS_Passenger_Data_FY17.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY18.csv.gz: \
		input/ARTS_Passenger_Data_FY18.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY19.csv.gz: \
		input/ARTS_Passenger_Data_FY19.csv.gz
	cd output && ln -sf ../$< .

# end.
