#
# :author: PN
# :maintainers: PN
# :date: 2019-03-19
# :license: GPL 2.0 or greater
#
# ice-air/import/src/Makefile
#
#

all: \
	output/ARTS_Data_Dictionary-reviewed.csv.gz \
	output/ARTS_Passenger_Data_FY11-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY12-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY13-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY14-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY15-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY16-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY17-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY18-redacted.csv.gz \
	output/ARTS_Passenger_Data_FY19_Year_To_Date-redacted.csv.gz \
	output/ARTS_Data_FY11-reviewed.csv.gz \
	output/ARTS_Data_FY12-reviewed.csv.gz \
	output/ARTS_Data_FY13-reviewed.csv.gz \
	output/ARTS_Data_FY14-reviewed.csv.gz \
	output/ARTS_Data_FY15-reviewed.csv.gz \
	output/ARTS_Data_FY16-reviewed.csv.gz \
	output/ARTS_Data_FY17-reviewed.csv.gz \
	output/ARTS_Data_FY18-reviewed.csv.gz \
	output/ARTS_Data_FY19_Year_To_Date-reviewed.csv.gz

output/ARTS_Data_Dictionary-reviewed.csv.gz: \
		input/ARTS_Data_Dictionary-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY11-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY11-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY12-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY12-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY13-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY13-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY14-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY14-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY15-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY15-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY16-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY16-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY17-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY17-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY18-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY18-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Passenger_Data_FY19_Year_To_Date-redacted.csv.gz: \
		input/ARTS_Passenger_Data_FY19_Year_To_Date-redacted.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY11-reviewed.csv.gz: \
		input/ARTS_Data_FY11-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY12-reviewed.csv.gz: \
		input/ARTS_Data_FY12-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY13-reviewed.csv.gz: \
		input/ARTS_Data_FY13-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY14-reviewed.csv.gz: \
		input/ARTS_Data_FY14-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY15-reviewed.csv.gz: \
		input/ARTS_Data_FY15-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY16-reviewed.csv.gz: \
		input/ARTS_Data_FY16-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY17-reviewed.csv.gz: \
		input/ARTS_Data_FY17-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY18-reviewed.csv.gz: \
		input/ARTS_Data_FY18-reviewed.csv.gz
	cd output && ln -sf ../$< .
output/ARTS_Data_FY19_Year_To_Date-reviewed.csv.gz: \
		input/ARTS_Data_FY19_Year_To_Date-reviewed.csv.gz
	cd output && ln -sf ../$< .

# end.
