#
# Authors:     PN
# Maintainers: PN
# Copyright:   2019, UWCHR, GPL v2 or later
# ============================================
# ice-air/docs/Makefile

.PHONY: all clean

all: \
	index.html

index.html: \
		../write/output/ice-air-data-appendix.html
	cp ../write/output/ice-air-data-appendix.html index.html